---
abstract: 'escape automatically in Template-Toolkit.'
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
build_requires:
  Test::Base: 0
  Test::More: 0
  URI: 0
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
keywords:
  - autoescape
  - autoescaping
  - escape
  - injection
  - security
  - stash
  - template
  - toolkit
  - xss
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Stash-AutoEscaping
provides:
  Template::Stash::AutoEscaping:
    file: lib/Template/Stash/AutoEscaping.pm
    version: 0.0303
  Template::Stash::AutoEscaping::Escaped::Base:
    file: lib/Template/Stash/AutoEscaping/Escaped/Base.pm
  Template::Stash::AutoEscaping::Escaped::HTML:
    file: lib/Template/Stash/AutoEscaping/Escaped/HTML.pm
  Template::Stash::AutoEscaping::Escaped::YourCode:
    file: lib/Template/Stash/AutoEscaping/Escaped/YourCode.pm
  Template::Stash::AutoEscaping::RawString:
    file: lib/Template/Stash/AutoEscaping/RawString.pm
requires:
  Class::Data::Inheritable: 0
  Data::Dumper: 0
  Template: 0
  Template::Config: 0
  Template::Exception: 0
  UNIVERSAL::require: 0
  base: 0
  overload: 0
  parent: 0
  perl: 5.012
  strict: 0
  warnings: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/shlomif/Template-Stash-AutoEscaping
version: 0.0303
