---
abstract: 'escape automatically in Template-Toolkit.'
author:
  - 'mala <cpan@ma.la> (original author of L<Template::Stash::AutoEscape>)'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Stash-AutoEscaping
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::Data::Inheritable: 0
  Filter::Util::Call: 0
  Template: 0
  UNIVERSAL::require: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/shlomif/Template-Stash-AutoEscape.git
version: 0.03
